# Elchi Endpoint Discovery Configuration
# All fields with their default values

# Elchi API configuration
elchi:
  # Bearer token for API authentication
  token: "sample-token-123"
  
  # API endpoint to send discovery results
  # Supports: http://host, https://host, http://host:port, https://host:port
  # Leave empty to disable API sending (only stdout output)
  api_endpoint: "https://api.example.com/discovery"
  
  # Skip TLS certificate verification (use with caution in production)
  insecure_skip_verify: false

# Logging configuration
log:
  # Log level: debug, info, warn, error
  level: "info"
  
  # Log format: text, json
  format: "text"
  
  # Log output: stdout, stderr
  output: "stdout"

# Discovery interval in seconds
# How often to scan and report cluster nodes
discovery_interval: 30

# Cluster name (REQUIRED)
# Must be set - no auto-detection
cluster_name: "my-kubernetes-cluster"