apiVersion: v2
name: elchi-endpoint-discovery
description: A Helm chart for Elchi Endpoint Discovery Plugin
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - elchi
  - kubernetes
  - endpoint-discovery
  - cloud-native
home: https://github.com/CloudNativeWorks/elchi-plugins
sources:
  - https://github.com/CloudNativeWorks/elchi-plugins
maintainers:
  - name: CloudNativeWorks
    email: support@cloudnativeworks.io